// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJS-EapZnR7CVuy-AIM5Ao3dGU_OLhyd0',
    appId: '1:232935353596:web:c06165ee8d64bdaa143b79',
    messagingSenderId: '232935353596',
    projectId: 'project-24b53',
    authDomain: 'project-24b53.firebaseapp.com',
    storageBucket: 'project-24b53.appspot.com',
    measurementId: 'G-PBGZMYYC59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYtOxjIaRs3afN9Z4Itxvbz0-fz9UZic',
    appId: '1:232935353596:android:2fdbf99f7428f3f4143b79',
    messagingSenderId: '232935353596',
    projectId: 'project-24b53',
    storageBucket: 'project-24b53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyalfSbJ9FpNXH0Agw5wj34q1ZcYidniI',
    appId: '1:232935353596:ios:fefa947167acbbb4143b79',
    messagingSenderId: '232935353596',
    projectId: 'project-24b53',
    storageBucket: 'project-24b53.appspot.com',
    iosClientId: '232935353596-0t0b74lbhcaqg1gpd62l034vmi13htk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app0',
  );
}
